apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarr.fullname" . }}
  labels:
    {{- include "sonarr.labels" . | nindent 4 }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ default 1 .Values.deployment.replicas }}
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}
  {{- with .Values.updateStrategy}}
  strategy:
    {{- toYaml . | nindent 4}}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sonarr.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sonarr.selectorLabels" . | nindent 8 }}
        {{- with .Values.deployment.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sonarr.serviceAccountName" . }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      dnsPolicy: {{.Values.deployment.dnsPolicy | default "ClusterFirst" }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
          - name: sonarr
            containerPort: {{ .Values.service.port }}
            protocol: TCP
          env:
          - name: PGID
            value: "{{ .Values.user.gid | default "1001" }}"
          - name: PUID
            value: "{{ .Values.user.uid | default "1001"  }}"
          - name: UMASK
            value: "{{ .Values.user.umask | default "022"  }}"
        {{- with .Values.deployment.additionalEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
          volumeMounts:
          - name: config
            mountPath: /config
            {{- if and (.Values.config.persistence.subPath) (.Values.config.persistence.enabled) }}
            subPath:
            {{- end }}
          - name: data
            mountPath: /data
            {{- if and (.Values.data.persistence.subPath) (.Values.config.persistence.enabled) }}
            subPath:
            {{- end }}
          {{- with .Values.deployment.additionalVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      volumes:
      - name: config
      {{- if .Values.config.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.config.persistence.existingClaim }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: data
      {{- if .Values.data.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.data.persistence.existingClaim }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- with .Values.deployment.additionalVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
