apiVersion: v1
kind: Service
metadata:
  name: {{ include "blocky.name" . }}
  labels:
    {{- include "blocky.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.service.dns.annotations }}
  annotations:
    {{- with .Values.service.dns.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.dns.type }}
  ports:
    - port: {{ .Values.service.dns.port }}
      targetPort: dns
      protocol: UDP
      name: dns
  selector:
    {{- include "blocky.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.dns.clusterIP }}
  clusterIP: {{ .Values.service.dns.clusterIP | quote }}
  {{- end }}
  {{- with .Values.service.dns.clusterIPs }}
  clusterIPs:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.service.dns.externalIPs }}
  externalIPs:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- if .Values.service.dns.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.dns.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if .Values.service.dns.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.service.dns.ipFamilyPolicy | quote }}
  {{- end }}
  {{- if .Values.service.dns.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.dns.loadBalancerIP | quote }}
  {{- end }}
  {{- with .Values.service.dns.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml . | nindent 2 }}
  {{- end }}