{{- if .Values.coredns.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "zones.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "zones.labels" . | nindent 4 }}
data:
  Corefile: |-
    {{- .Values.coredns.config | nindent 4 -}}
{{- end }}