{{- if not .Values.coredns.existingConfig.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dns.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "dns.labels" . | nindent 4 }}
data:
  Corefile: |-
    {{- .Values.coredns.config | nindent 4 -}}
{{- end }}