apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dns.fullname" . }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "dns.labels" . | nindent 4 }}
    {{- with .Values.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.updateStrategy}}
  strategy:
    {{- toYaml . | nindent 4}}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "dns.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dns.serviceAccountName" . }}
      {{- with .Values.initContainers }}
      initContainers:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      dnsPolicy: {{.Values.dnsPolicy | default "ClusterFirst" }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "coredns"
          {{- if .Values.securityContext }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args: [ "-conf", "/etc/coredns/Corefile" ]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: dns
            containerPort: 53
            protocol: UDP
          {{- with .Values.additionalPorts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/coredns
          {{- range .Values.extraSecrets }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            readOnly: true
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
          {{- toYaml .Values.extraVolumeMounts | nindent 8}}
          {{- end }}
      {{- with .Values.extraContainers }}
      {{ toYaml .Values.extraContainers | indent 6 }}
      {{- end }}
      volumes:
        - name: config-volume
        {{- if not .Values.coredns.existingConfig.enabled }}
          configMap:
            name: {{ template "dns.fullname" . }}
            items:
            - key: Corefile
              path: Corefile
        {{- else }}
          configMap:
            name: {{ .Values.coredns.existingConfig.name }}
            items:
            - key: {{ .Values.coredns.existingConfig.key }}
              path: Corefile
        {{- end }}

{{- range .Values.extraSecrets }}
        - name: {{ .name }}
          secret:
            secretName: {{ .name }}
            defaultMode: {{ default 400 .defaultMode }}
{{- end }}
{{- if .Values.extraVolumes }}
{{ toYaml .Values.extraVolumes | indent 8 }}
{{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
