name: '[CI/CD] [Charts] Build & Push chart'

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - 'release/**'
      - 'hotfix/**'
    paths:
      - 'charts/**'
      - '!**.md'

jobs:
  modified:
    name: 'Get modified charts'
    runs-on: ubuntu-latest
    outputs:
      chart: ${{ steps.check.outputs.chart }}
      chart_path: ${{ steps.check.outputs.chart_path }}
      chart_output: ${{ steps.check.outputs.chart_output }}
      result: ${{ steps.check.outputs.result }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - id: check
      run: |
        make check
  build:
    name: 'Build modified chart'
    runs-on: ubuntu-latest
    needs: modified
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - uses: actions/setup-python@v4
    - run: sudo apt-get install -y git-filter-repo
    - uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: |
        git-filter-repo --subdirectory-filter ${{ needs.modified.outputs.chart_path }} &&
        git remote add origin https://github.com/ganawaj/${{ needs.modified.outputs.chart}}-helm.git
    - uses: gittools/actions/gitversion/execute@v0
      id: gitversion
    - run: |
        helm package . --version ${{ steps.gitversion.outputs.semVer }}
    - name: Archive helm artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          *.tgz
  helm:
    name: Upload OCI Helm chart to Dockerhub
    needs:
    - build
    - modified
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          scripts
          Makefile
        sparse-checkout-cone-mode: false
    - uses: actions/download-artifact@v4
    - run: make helm
      env:
        CHART: "${{ needs.modified.outputs.chart}}-${{ needs.build.outputs.version }}.tgz"
        USER: "${{ secrets.DOCKERHUB_USER }}"
        PASS: "${{ secrets.DOCKERHUB_PASS }}"
        REGISTRY: "oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USER }}"
